
import { z } from 'zod';

// --- Helper Schemas ---

const PhoneSchema = z.string().min(8, "Telefoonnummer is te kort").max(20, "Telefoonnummer is te lang");

// --- Customer Schema ---

export const CustomerSchema = z.object({
  id: z.string().optional(),
  salutation: z.string().optional(),
  firstName: z.string().min(1, "Voornaam is verplicht"),
  lastName: z.string().min(1, "Achternaam is verplicht"),
  email: z.string().email("Ongeldig e-mailadres"),
  phone: PhoneSchema,
  street: z.string().min(1, "Straatnaam is verplicht"),
  houseNumber: z.string().min(1, "Huisnummer is verplicht"),
  zip: z.string().min(4, "Postcode is verplicht"),
  city: z.string().min(1, "Woonplaats is verplicht"),
  country: z.string().default('NL'),
  companyName: z.string().optional(),
  vatNumber: z.string().optional(),
  billingAddress: z.object({
    street: z.string().optional(),
    houseNumber: z.string().optional(),
    zip: z.string().optional(),
    city: z.string().optional(),
    country: z.string().optional(),
  }).optional(),
  isBusiness: z.boolean().optional(),
  notes: z.string().optional(),
  birthday: z.string().optional(), // YYYY-MM-DD
  tags: z.array(z.string()).optional()
});

// --- Reservation Schema ---

export const ReservationSchema = z.object({
  id: z.string().optional(), // Generated by backend/storage usually
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Ongeldige datum"),
  showId: z.string().min(1, "Show ID is verplicht"),
  partySize: z.number().min(1, "Aantal personen moet minimaal 1 zijn").max(250, "Groep is te groot"),
  packageType: z.enum(['standard', 'premium']),
  customer: CustomerSchema,
  status: z.enum(['REQUEST', 'OPTION', 'CONFIRMED', 'ARRIVED', 'CANCELLED', 'WAITLIST', 'INVITED', 'ARCHIVED', 'NOSHOW']).optional(),
  addons: z.array(z.object({
    id: z.string(),
    quantity: z.number().min(0)
  })).optional(),
  merchandise: z.array(z.object({
    id: z.string(),
    quantity: z.number().min(0)
  })).optional(),
  notes: z.object({
    dietary: z.string().optional(),
    structuredDietary: z.record(z.number()).optional(),
    comments: z.string().optional(),
    isCelebrating: z.boolean().optional(),
    celebrationText: z.string().optional(),
    internal: z.string().optional()
  }).optional(),
  idempotencyKey: z.string().optional()
});

export type ValidatedCustomer = z.infer<typeof CustomerSchema>;
export type ValidatedReservation = z.infer<typeof ReservationSchema>;
